version: "2.1"
services:
  fast:
    build:
      context: ./fast
    depends_on:
      - slow
  slow:
    build:
      context: ./slow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://slow:8080"]
      interval: 1s
      timeout: 2s
      retries: 3
