version: "2.1"
services:
  fast:
    build:
      context: ./fast
    depends_on:
      slow:
        condition: service_healthy
  slow:
    build:
      context: ./slow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://slow:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
